import { icon } from '../core/icons.js';
import { badge, downloadFile, emptyState, objectsToCsv, openDrawer, pageHeader, pagination, toast } from '../components/ui.js';
import { escapeHtml, relativeTime } from '../core/utils.js';

const view = { query: '', actor: 'all', result: 'all' };
let filterTimer;
const actionLabels = {
  QUALITY_GATE_APPROVED: '质量门禁通过', INGESTION_BLOCKED: '摄取任务阻断', SOURCE_SYNCED: '知识源同步', SOURCE_CREATED: '创建知识源', SOURCE_UPDATED: '更新知识源', SOURCE_PAUSED: '暂停知识源', SOURCE_RESUMED: '恢复知识源', SOURCE_ARCHIVED: '归档知识源', INGESTION_JOB_CREATED: '创建摄取任务', JOB_STARTED: '启动摄取任务', JOB_RESUMED: '恢复摄取任务', JOB_CANCELED: '取消摄取任务', INGESTION_COMPLETED: '摄取完成', REVIEW_ITEM_RESOLVED: '保存复核决定', MANUAL_REVIEW_COMPLETED: '完成人工复核', EVALUATION_STARTED: '启动质量评测', EVALUATION_DATASET_CREATED: '创建评测集', ALIAS_ACTIVATED: '发布版本', ALIAS_ROLLED_BACK: '回滚版本', SETTINGS_UPDATED: '更新环境配置', CONNECTION_TESTED: '连接测试', CREDENTIAL_ROTATED: '凭据轮换', WORKSPACE_SWITCHED: '切换工作空间',
};

function filtered(state) {
  const q = view.query.toLowerCase();
  return state.audits.filter((item) => (view.actor === 'all' || item.actor === view.actor) && (view.result === 'all' || item.result === view.result) && (!q || `${item.action} ${item.target} ${item.requestId} ${item.detail}`.toLowerCase().includes(q)));
}

function detailDrawer(item) {
  openDrawer({ title: actionLabels[item.action] || item.action, subtitle: `${item.actor} · ${relativeTime(item.time)}`, body: `<div class="notice ${item.result === 'success' ? 'success' : 'danger'}">${icon(item.result === 'success' ? 'checkCircle' : 'alert')}<div><strong>${item.result === 'success' ? '操作成功并已留痕' : '操作被策略拒绝或阻断'}</strong><span>${escapeHtml(item.detail)}</span></div></div><dl class="detail-list form-section"><div><dt>事件类型</dt><dd class="mono">${escapeHtml(item.action)}</dd></div><div><dt>操作结果</dt><dd>${badge(item.result)}</dd></div><div><dt>目标资源</dt><dd>${escapeHtml(item.target)}</dd></div><div><dt>操作人</dt><dd>${escapeHtml(item.actor)}</dd></div><div><dt>来源 IP / 服务</dt><dd class="mono">${escapeHtml(item.ip)}</dd></div><div><dt>Request ID</dt><dd class="mono">${escapeHtml(item.requestId)}</dd></div><div><dt>事件时间</dt><dd>${escapeHtml(new Date(item.time).toLocaleString('zh-CN', { hour12: false }))}</dd></div><div><dt>保存周期</dt><dd>180 天（模拟策略）</dd></div></dl>`, actions: [{ label: '导出本条证据', variant: 'primary', icon: 'download', onClick: () => { downloadFile(`${item.requestId}.json`, JSON.stringify(item, null, 2)); toast('审计证据已导出', 'success'); } }] });
}

export function renderAudit(state, route) {
  if (route?.query?.get('actor') && view.actor === 'all') view.actor = route.query.get('actor');
  const rows = filtered(state); const actors = [...new Set(state.audits.map((item) => item.actor))];
  return `${pageHeader({ title: '权限审计', description: '追踪知识源、摄取、评测、发布与配置变更，为权限复核和事故追溯提供证据。', actions: `<button class="button secondary" type="button" id="exportJson">${icon('download')}导出 JSON</button><button class="button primary" type="button" id="exportCsv">${icon('download')}导出 CSV</button>` })}<section class="panel"><div class="filter-bar"><label class="filter-search">${icon('search')}<input id="auditSearch" type="search" value="${escapeHtml(view.query)}" placeholder="搜索事件、资源或 request_id"></label><label class="filter-control"><span>操作人</span><select id="auditActor"><option value="all">全部操作人</option>${actors.map((actor) => `<option value="${escapeHtml(actor)}" ${view.actor === actor ? 'selected' : ''}>${escapeHtml(actor)}</option>`).join('')}</select></label><label class="filter-control"><span>结果</span><select id="auditResult"><option value="all">全部结果</option><option value="success" ${view.result === 'success' ? 'selected' : ''}>成功</option><option value="denied" ${view.result === 'denied' ? 'selected' : ''}>阻断 / 拒绝</option></select></label><button class="button ghost small" type="button" id="resetAudit">重置</button></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th style="width:31%">审计事件</th><th style="width:13%">操作人</th><th style="width:12%">结果</th><th style="width:17%">来源</th><th style="width:18%">Request ID</th><th style="width:9%"></th></tr></thead><tbody>${rows.map((item) => `<tr><td><button class="audit-event table-link-block" type="button" data-audit="${item.id}"><span class="audit-icon">${icon(item.action.includes('ALIAS') ? 'boxes' : item.action.includes('QUALITY') || item.action.includes('EVALUATION') ? 'activity' : item.action.includes('SOURCE') ? 'file' : 'shield')}</span><span><strong>${escapeHtml(actionLabels[item.action] || item.action)}</strong><small>${escapeHtml(item.target)} · ${escapeHtml(relativeTime(item.time))}</small></span></button></td><td>${escapeHtml(item.actor)}</td><td>${badge(item.result)}</td><td><strong class="mono">${escapeHtml(item.ip)}</strong></td><td><span class="mono">${escapeHtml(item.requestId)}</span></td><td><div class="table-actions"><button class="icon-button compact" type="button" data-audit="${item.id}" aria-label="查看审计详情" title="查看证据">${icon('eye')}</button></div></td></tr>`).join('') || `<tr><td colspan="6">${emptyState('没有匹配的审计事件', '调整筛选条件后重新查看。')}</td></tr>`}</tbody></table></div>${pagination(rows.length, '条审计事件')}</section><div class="notice info page-note">${icon('lock')}<div><strong>审计日志在真实系统中应写入不可篡改存储</strong><span>本页面只在当前内存中模拟审计记录，刷新后恢复初始数据。生产环境需要服务端签名、集中留存和独立读取权限。</span></div></div>`;
}

export function mountAudit(root, state, rerender) {
  const apply = () => { view.query = root.querySelector('#auditSearch').value; view.actor = root.querySelector('#auditActor').value; view.result = root.querySelector('#auditResult').value; rerender(); };
  root.querySelector('#auditSearch').addEventListener('input', () => { window.clearTimeout(filterTimer); filterTimer = window.setTimeout(apply, 180); }); root.querySelector('#auditActor').addEventListener('change', apply); root.querySelector('#auditResult').addEventListener('change', apply);
  root.querySelector('#resetAudit').addEventListener('click', () => { view.query = ''; view.actor = 'all'; view.result = 'all'; rerender(); });
  const rows = filtered(state); root.querySelector('#exportJson').addEventListener('click', () => { downloadFile('knowledge-audit-evidence.json', JSON.stringify(rows, null, 2)); toast(`已导出 ${rows.length} 条审计证据`, 'success'); });
  root.querySelector('#exportCsv').addEventListener('click', () => { downloadFile('knowledge-audit-evidence.csv', objectsToCsv(rows, [{ key: 'time', label: '时间' }, { key: 'actor', label: '操作人' }, { key: 'action', label: '事件' }, { key: 'target', label: '目标' }, { key: 'result', label: '结果' }, { key: 'ip', label: '来源' }, { key: 'requestId', label: 'Request ID' }, { key: 'detail', label: '详情' }]), 'text/csv;charset=utf-8'); toast(`已导出 ${rows.length} 条 CSV 记录`, 'success'); });
  root.querySelectorAll('[data-audit]').forEach((button) => button.addEventListener('click', () => detailDrawer(state.audits.find((item) => item.id === button.dataset.audit))));
}
