import { icon } from '../core/icons.js';
import { rotateCredential, saveSettings, testConnection } from '../core/mock-api.js';
import { badge, confirmAction, pageHeader, panel, toast } from '../components/ui.js';
import { escapeHtml, relativeTime } from '../core/utils.js';

let activeTab = 'infrastructure';
const tabs = [['infrastructure','基础设施'],['models','模型服务'],['connectors','内容连接器'],['security','安全策略']];

function connectionRow(key, iconName, title, subtitle, setting, credential = false) {
  return `<div class="connector-row"><span>${icon(iconName)}</span><div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(subtitle)} · ${setting.lastCheckedAt ? `检查于 ${relativeTime(setting.lastCheckedAt)}` : '尚未检查'}</small></div>${badge(setting.status)}<div class="table-actions"><button class="button secondary small" type="button" data-test="${key}">${icon('activity')}连接测试</button>${credential ? `<button class="icon-button compact" type="button" data-rotate="${key}" aria-label="轮换 ${escapeHtml(title)} 凭据" title="轮换凭据">${icon('key')}</button>` : ''}</div></div>`;
}

function tabBody(state) {
  const s = state.settings;
  if (activeTab === 'infrastructure') return panel({ title: '向量存储与版本别名', description: '发布操作只切换别名，不覆盖不可变 Collection。', body: `<form id="infrastructureForm"><div class="form-grid"><label class="field span-full"><span>Milvus URI</span><input name="uri" value="${escapeHtml(s.milvus.uri)}"></label><label class="field"><span>Collection 前缀</span><input name="collectionPrefix" value="${escapeHtml(s.milvus.collectionPrefix)}"></label><label class="field"><span>线上检索别名</span><input name="activeAlias" value="${escapeHtml(s.milvus.activeAlias)}"></label></div><div class="form-actions"><button class="button secondary" type="button" data-test="milvus">${icon('activity')}连接测试</button><button class="button primary" type="submit">${icon('check')}保存配置</button></div></form>` });
  if (activeTab === 'models') return `<div class="stack">${panel({ title: 'Embedding 服务', body: `<form id="embeddingForm"><div class="form-grid"><label class="field"><span>Provider</span><input name="provider" value="${escapeHtml(s.embedding.provider)}"></label><label class="field"><span>模型</span><input name="model" value="${escapeHtml(s.embedding.model)}"></label><label class="field"><span>向量维度</span><input name="dimensions" type="number" value="${s.embedding.dimensions}"></label></div><div class="form-actions"><button class="button secondary" type="button" data-test="embedding">${icon('activity')}调用测试</button><button class="button primary" type="submit">${icon('check')}保存</button></div></form>` })}${panel({ title: 'Reranker 服务', body: `<form id="rerankerForm"><div class="form-grid"><label class="field"><span>Provider</span><input name="provider" value="${escapeHtml(s.reranker.provider)}"></label><label class="field"><span>模型</span><input name="model" value="${escapeHtml(s.reranker.model)}"></label><label class="field"><span>超时（秒）</span><input name="timeoutSeconds" type="number" step="0.1" value="${s.reranker.timeoutSeconds}"></label></div><div class="form-actions"><button class="button secondary" type="button" data-test="reranker">${icon('activity')}调用测试</button><button class="button primary" type="submit">${icon('check')}保存</button></div></form>` })}</div>`;
  if (activeTab === 'connectors') return panel({ title: '内容连接器', description: '凭据由 Vault 托管，前端只保存引用。', body: `${connectionRow('wiki','book','企业 Wiki',s.wiki.baseUrl,s.wiki,true)}${connectionRow('objectStorage','database','对象存储',`${s.objectStorage.endpoint} / ${s.objectStorage.bucket}`,s.objectStorage,true)}<div class="notice info form-section">${icon('key')}<div><strong>轮换采用双凭据窗口</strong><span>新凭据连接测试通过后再撤销旧凭据，避免定时同步中断。</span></div></div>` });
  return panel({ title: '安全与留存策略', description: '这些约束会在摄取预检、发布和审计链路中强制执行。', body: `<form id="securityForm"><div class="setting-block"><div class="setting-block-header"><div><h3>发布需要审批</h3><p>候选版本通过质量门禁后，仍需 release_manager 确认。</p></div><label class="switch"><input name="requireApproval" type="checkbox" ${s.security.requireApproval ? 'checked' : ''}><span></span></label></div></div><div class="setting-block"><div class="setting-block-header"><div><h3>阻断高风险删除</h3><p>删除占比超过阈值时停止摄取，要求人工复核。</p></div><label class="switch"><input name="blockHighRiskDelete" type="checkbox" ${s.security.blockHighRiskDelete ? 'checked' : ''}><span></span></label></div><label class="field"><span>高风险删除阈值（%）</span><input name="highRiskDeletePercent" type="number" min="1" max="50" value="${s.security.highRiskDeletePercent}"></label></div><div class="form-grid setting-block"><label class="field"><span>保留可回滚版本数</span><input name="retainVersions" type="number" min="2" max="20" value="${s.security.retainVersions}"></label><label class="field"><span>审计留存天数</span><input name="auditRetentionDays" type="number" min="30" value="${s.security.auditRetentionDays}"></label></div><div class="form-actions"><button class="button primary" type="submit">${icon('shield')}保存安全策略</button></div></form>` });
}

export function renderSettings(state) {
  return `${pageHeader({ title: '环境配置', description: '管理模拟环境的向量存储、模型、内容连接器与安全约束。', actions: `<span class="environment-badge"><i></i>模拟环境</span>` })}<nav class="settings-nav" aria-label="配置分类">${tabs.map(([key,label]) => `<button class="${activeTab === key ? 'active' : ''}" type="button" data-settings-tab="${key}">${label}</button>`).join('')}</nav><div class="settings-content">${tabBody(state)}</div><div class="notice warning page-note">${icon('alert')}<div><strong>此页面使用模拟 API</strong><span>操作只更新当前页面的内存状态与模拟审计，刷新浏览器后自动恢复初始数据，不会访问真实基础设施。</span></div></div>`;
}

function values(form) {
  const result = {}; new FormData(form).forEach((value, key) => { const field = form.elements[key]; result[key] = field.type === 'number' ? Number(value) : value; });
  form.querySelectorAll('input[type="checkbox"]').forEach((input) => { result[input.name] = input.checked; }); return result;
}

export function mountSettings(root, _state, rerender) {
  root.querySelectorAll('[data-settings-tab]').forEach((button) => button.addEventListener('click', () => { activeTab = button.dataset.settingsTab; rerender(); }));
  root.querySelectorAll('[data-test]').forEach((button) => button.addEventListener('click', async () => { button.disabled = true; const original = button.innerHTML; button.textContent = '检查中'; try { await testConnection(button.dataset.test); toast('连接、认证与最小权限检查通过', 'success'); } catch (error) { button.disabled = false; button.innerHTML = original; toast(error.message, 'danger'); } }));
  root.querySelectorAll('[data-rotate]').forEach((button) => button.addEventListener('click', async () => { const section = button.dataset.rotate; const yes = await confirmAction({ title: '轮换连接器凭据', message: '确认生成新的 Vault 凭据引用？', confirmLabel: '开始轮换', detail: '模拟流程会先验证新凭据，再更新引用并记录审计事件。' }); if (yes) { await rotateCredential(section); toast('凭据轮换完成', 'success'); } }));
  const forms = [['infrastructureForm','milvus'],['embeddingForm','embedding'],['rerankerForm','reranker'],['securityForm','security']];
  forms.forEach(([id, section]) => root.querySelector(`#${id}`)?.addEventListener('submit', async (event) => { event.preventDefault(); const button = event.currentTarget.querySelector('[type="submit"]'); button.disabled = true; try { await saveSettings(section, values(event.currentTarget)); toast('配置已保存并记录审计', 'success'); } catch (error) { button.disabled = false; toast(error.message, 'danger'); } }));
}
