import { icon } from '../core/icons.js';
import { activateVersion, rollbackVersion } from '../core/mock-api.js';
import { navigate } from '../core/router.js';
import { badge, confirmAction, openDrawer, openModal, pageHeader, toast } from '../components/ui.js';
import { escapeHtml, formatNumber, relativeTime } from '../core/utils.js';
let openedVersionQuery = '';

function versionDetail(version) {
  openDrawer({ title: version.collection, subtitle: version.status === 'active' ? '当前线上版本' : '离线 Collection', body: `<div class="summary-grid"><div><span>状态</span>${badge(version.status)}</div><div><span>质量门禁</span>${badge(version.qualityGate)}</div><div><span>质量分</span><strong>${version.qualityScore ?? '--'}</strong></div><div><span>创建时间</span><strong>${escapeHtml(relativeTime(version.createdAt))}</strong></div></div><dl class="detail-list form-section"><div><dt>Collection</dt><dd class="mono">${escapeHtml(version.collection)}</dd></div><div><dt>检索别名</dt><dd class="mono">${escapeHtml(version.alias || '未绑定')}</dd></div><div><dt>文档数</dt><dd>${formatNumber(version.documents)}</dd></div><div><dt>Chunk 数</dt><dd>${formatNumber(version.chunks)}</dd></div><div><dt>来源任务</dt><dd class="mono">${escapeHtml(version.sourceJobId)}</dd></div><div><dt>操作人</dt><dd>${escapeHtml(version.operator)}</dd></div></dl><div class="notice info form-section">${icon('clipboard')}<div><strong>版本说明</strong><span>${escapeHtml(version.notes || '暂无版本说明')}</span></div></div>`, actions: [{ label: '查看评测报告', icon: 'activity', onClick: () => navigate('/quality', { version: version.id }) }] });
}

function compareVersions(state) {
  const eligible = state.versions.filter((item) => item.status !== 'archived');
  const active = state.versions.find((item) => item.status === 'active') || eligible[0];
  const other = eligible.find((item) => item.id !== active.id) || active;
  const options = (selected) => eligible.map((item) => `<option value="${item.id}" ${item.id === selected ? 'selected' : ''}>${escapeHtml(item.collection)}</option>`).join('');
  const renderResult = (left, right) => `<div class="comparison-result"><div class="metric-bar"><label>文档变化</label><div class="progress"><span style="width:${Math.min(100, Math.abs(right.documents - left.documents) / 2 + 10)}%"></span></div><strong>${right.documents - left.documents >= 0 ? '+' : ''}${formatNumber(right.documents - left.documents)}</strong></div><div class="metric-bar"><label>Chunk 变化</label><div class="progress"><span style="width:${Math.min(100, Math.abs(right.chunks - left.chunks) / 1000 + 10)}%"></span></div><strong>${right.chunks - left.chunks >= 0 ? '+' : ''}${formatNumber(right.chunks - left.chunks)}</strong></div><div class="metric-bar"><label>质量分变化</label><div class="progress success"><span style="width:${Math.max(5, right.qualityScore || 0)}%"></span></div><strong>${((right.qualityScore || 0) - (left.qualityScore || 0)).toFixed(1)}</strong></div><div class="notice ${right.qualityGate === 'passed' ? 'success' : 'warning'}">${icon(right.qualityGate === 'passed' ? 'checkCircle' : 'alert')}<div><strong>${right.qualityGate === 'passed' ? '目标版本满足发布条件' : '目标版本尚不可发布'}</strong><span>比较只读取不可变 Collection 指标，不会改变线上别名。</span></div></div></div>`;
  openModal({ title: '版本对比', subtitle: '比较两个不可变 Collection 的规模与质量指标。', size: 'wide', body: `<div class="comparison-grid"><label class="field"><span>基线版本</span><select id="compareLeft">${options(active.id)}</select></label><span class="comparison-arrow">${icon('arrowRight')}</span><label class="field"><span>目标版本</span><select id="compareRight">${options(other.id)}</select></label></div><div class="form-section" id="compareResult">${renderResult(active, other)}</div>`, actions: [{ label: '关闭' }], onMount: (modal) => { const update = () => { const left = state.versions.find((item) => item.id === modal.querySelector('#compareLeft').value); const right = state.versions.find((item) => item.id === modal.querySelector('#compareRight').value); modal.querySelector('#compareResult').innerHTML = renderResult(left, right); }; modal.querySelector('#compareLeft').addEventListener('change', update); modal.querySelector('#compareRight').addEventListener('change', update); } });
}

export function renderVersions(state) {
  const active = state.versions.find((item) => item.status === 'active');
  return `${pageHeader({ title: '版本发布', description: '通过不可变 Collection 与原子别名切换发布知识库；质量门禁不通过时禁止上线。', actions: `<button class="button secondary" type="button" id="compareVersions">${icon('sliders')}版本对比</button><button class="button primary" type="button" id="goQuality">${icon('activity')}质量评测</button>` })}<section class="version-hero"><div><small>线上检索别名</small><strong class="online mono">${escapeHtml(active?.alias || '--')}</strong></div><div><small>当前 Collection</small><strong class="mono">${escapeHtml(active?.collection || '--')}</strong></div><div><small>线上质量分</small><span class="quality-score"><strong>${active?.qualityScore?.toFixed(1) || '--'}</strong><small>/ 100</small></span></div><div><small>安全策略</small><strong>CAS 切换 · 保留 ${state.settings.security.retainVersions} 个版本</strong></div></section><section class="panel"><div class="data-table-wrap"><table class="data-table"><thead><tr><th style="width:27%">Collection</th><th style="width:12%">状态</th><th style="width:13%">质量门禁</th><th style="width:17%">内容规模</th><th style="width:14%">创建信息</th><th style="width:17%">操作</th></tr></thead><tbody>${state.versions.map((version) => `<tr><td><button class="table-link-block" type="button" data-version-open="${version.id}"><strong class="mono">${escapeHtml(version.collection)}</strong><small>${escapeHtml(version.notes)}</small></button></td><td>${badge(version.status)}</td><td>${badge(version.qualityGate)}<small>${version.qualityScore == null ? '尚未评分' : `${version.qualityScore.toFixed(1)} 分`}</small></td><td><strong>${formatNumber(version.documents)} 文档</strong><small>${formatNumber(version.chunks)} chunks</small></td><td><strong>${escapeHtml(version.operator)}</strong><small>${escapeHtml(relativeTime(version.createdAt))}</small></td><td><div class="table-actions">${version.status === 'candidate' ? `<button class="button primary small" type="button" data-activate="${version.id}" ${version.qualityGate !== 'passed' ? 'disabled title="质量门禁未通过"' : ''}>${icon('rocket')}发布</button>` : ['ready','archived'].includes(version.status) ? `<button class="button secondary small" type="button" data-rollback="${version.id}" ${version.qualityGate !== 'passed' ? 'disabled title="质量门禁未通过"' : ''}>${icon('history')}回滚至此</button>` : ''}<button class="icon-button compact" type="button" data-version-open="${version.id}" aria-label="查看版本详情" title="查看详情">${icon('eye')}</button></div></td></tr>`).join('')}</tbody></table></div></section><div class="notice info page-note">${icon('shield')}<div><strong>发布不会覆盖 Collection</strong><span>系统先校验质量门禁与当前别名版本，再原子切换 rag_active；旧版本保留，可一键回滚。</span></div></div>`;
}

export function mountVersions(root, state, _rerender, route) {
  root.querySelector('#compareVersions').addEventListener('click', () => compareVersions(state)); root.querySelector('#goQuality').addEventListener('click', () => navigate('/quality'));
  root.querySelectorAll('[data-version-open]').forEach((button) => button.addEventListener('click', () => versionDetail(state.versions.find((item) => item.id === button.dataset.versionOpen))));
  root.querySelectorAll('[data-activate]').forEach((button) => button.addEventListener('click', async () => { const version = state.versions.find((item) => item.id === button.dataset.activate); const yes = await confirmAction({ title: '发布候选版本', message: `将 rag_active 切换至 ${version.collection}？`, confirmLabel: '确认发布', detail: `质量分 ${version.qualityScore}，当前线上版本将保留为回滚目标。` }); if (yes) { await activateVersion(version.id); toast('版本发布成功，线上别名已切换', 'success'); } }));
  root.querySelectorAll('[data-rollback]').forEach((button) => button.addEventListener('click', async () => { const version = state.versions.find((item) => item.id === button.dataset.rollback); const yes = await confirmAction({ title: '回滚线上版本', message: `将 rag_active 回滚至 ${version.collection}？`, confirmLabel: '确认回滚', danger: true, detail: '系统会校验当前别名，避免覆盖其他管理员刚完成的发布。' }); if (yes) { await rollbackVersion(version.id); toast('版本回滚完成', 'success'); } }));
  const requested = route?.query?.get('version');
  if (!requested) openedVersionQuery = '';
  if (requested && requested !== openedVersionQuery) {
    openedVersionQuery = requested;
    const version = state.versions.find((item) => item.id === requested);
    if (version) window.setTimeout(() => versionDetail(version), 0);
  }
}
