const iso = (day, time) => `2026-09-${day}T${time}:00+08:00`;

export function createSeedData() {
  return {
    schemaVersion: 3,
    meta: { updatedAt: iso('05', '18:00'), resetCount: 0 },
    workspaces: [
      { id: 'crm-demo', name: '商业平台 · 客户运营', monogram: '商', role: '知识库管理员' },
      { id: 'crm-enterprise', name: '大客户业务支持', monogram: '大', role: '只读审计员' },
      { id: 'crm-north', name: '华北渠道运营', monogram: '北', role: '内容运营' },
    ],
    activeWorkspaceId: 'crm-demo',
    user: { id: 'user-liwen', name: '李雯', title: '知识库运营', roles: ['knowledge_admin', 'release_manager'] },
    sources: [
      { id: 'src-product', name: '商业产品能力与计费规则', type: 'markdown', category: '产品政策', owner: '张凯', tenantId: 'crm-demo', visibility: 'restricted', acl: ['group:sales', 'group:customer-success'], status: 'active', health: 'healthy', documents: 28640, chunks: 412780, version: 'v2026.09.01', lastSync: iso('01', '21:24'), uri: 'datas/md/product-policy', schedule: '手动' },
      { id: 'src-sales-sop', name: '销售与客户成功 SOP', type: 'wiki', category: '服务流程', owner: '李雯', tenantId: 'crm-demo', visibility: 'restricted', acl: ['group:sales', 'group:customer-success'], status: 'active', health: 'warning', documents: 41200, chunks: 638420, version: 'wiki-r1842', lastSync: iso('05', '16:40'), uri: 'wiki://crm/sales-sop', schedule: '每 30 分钟' },
      { id: 'src-account-risk', name: '账户审核与风险处置规范', type: 'object', category: '风险合规', owner: '周涵', tenantId: 'crm-demo', visibility: 'restricted', acl: ['group:crm-ops', 'group:risk-control'], status: 'active', health: 'healthy', documents: 18620, chunks: 286340, version: 'oss-20260904', lastSync: iso('04', '23:10'), uri: 's3://crm-kb/risk-control', schedule: '每日 02:00' },
      { id: 'src-assignment', name: '客户归属与区域协同规则', type: 'markdown', category: '客户规则', owner: '陈静', tenantId: 'crm-demo', visibility: 'restricted', acl: ['group:sales', 'group:crm-ops'], status: 'paused', health: 'paused', documents: 6240, chunks: 76480, version: 'v2026.08.28', lastSync: '2026-08-28T19:12:00+08:00', uri: 'datas/md/customer-assignment', schedule: '手动' },
      { id: 'src-troubleshoot', name: '投放平台故障排查手册', type: 'wiki', category: '故障排查', owner: '刘阳', tenantId: 'crm-demo', visibility: 'restricted', acl: ['group:customer-success', 'group:platform-support'], status: 'active', health: 'healthy', documents: 21400, chunks: 321980, version: 'wiki-r319', lastSync: iso('05', '17:20'), uri: 'wiki://crm/troubleshooting', schedule: '每小时' },
      { id: 'src-announcement', name: '运营公告与活动说明', type: 'markdown', category: '运营公告', owner: '赵蕾', tenantId: 'crm-demo', visibility: 'public', acl: [], status: 'syncing', health: 'syncing', documents: 300, chunks: 4000, version: 'v2026.09.05', lastSync: iso('05', '17:56'), uri: 'datas/md/announcements', schedule: '手动' },
    ],
    jobs: [
      { id: 'job-0905-004', runId: 'crm-demo-20260905-004', sourceId: 'src-announcement', sourceName: '运营公告与活动说明', type: 'incremental', status: 'running', progress: 68, stage: '写入 Chunk', createdAt: iso('05', '17:56'), updatedAt: iso('05', '17:58'), operator: '赵蕾', added: 18, updated: 4, removed: 0, unchanged: 278, attempts: 1, logs: ['17:56:02 已生成摄取计划', '17:56:08 开始解析 Markdown', '17:57:14 已写入 3,200 / 4,700 Chunk'] },
      { id: 'job-0905-003', runId: 'crm-demo-20260905-003', sourceId: 'src-sales-sop', sourceName: '销售与客户成功 SOP', type: 'incremental', status: 'failed', progress: 42, stage: '等待人工复核', createdAt: iso('05', '16:40'), updatedAt: iso('05', '16:43'), operator: '李雯', added: 12, updated: 7, removed: 1, unchanged: 390, attempts: 2, reviewRequired: true, reviewStatus: 'pending', reviewId: 'review-0905-003', error: '检测到 3 个包含合并单元格的表格，需要人工复核', logs: ['16:40:04 获取 Wiki 快照成功', '16:41:31 解析 172 / 410 篇文档', '16:43:09 质量规则 TABLE_STRUCTURE 阻断任务'] },
      { id: 'job-0901-003', runId: 'crm-demo-20260901-003', sourceId: 'src-product', sourceName: '商业产品能力与计费规则', type: 'versioned', status: 'completed', progress: 100, stage: '完成', createdAt: iso('01', '20:15'), updatedAt: iso('01', '21:31'), operator: '李雯', added: 64, updated: 31, removed: 8, unchanged: 28481, attempts: 1, candidateVersionId: 'ver-active', logs: ['20:15:02 计划生成完成', '20:35:44 治理字段校验通过', '21:26:18 Collection 构建完成', '21:31:50 等待发布'] },
      { id: 'job-0828-002', runId: 'crm-demo-20260828-002', sourceId: 'src-assignment', sourceName: '客户归属与区域协同规则', type: 'versioned', status: 'completed', progress: 100, stage: '恢复后完成', createdAt: '2026-08-28T18:20:00+08:00', updatedAt: '2026-08-28T19:12:00+08:00', operator: '陈静', added: 4, updated: 8, removed: 0, unchanged: 6228, attempts: 2, candidateVersionId: 'ver-ready', logs: ['18:20:08 开始构建', '18:49:21 Milvus 写入超时', '18:55:00 从 checkpoint 恢复', '19:12:34 构建完成'] },
      { id: 'job-0826-001', runId: 'crm-demo-20260826-001', sourceId: 'src-troubleshoot', sourceName: '投放平台故障排查手册', type: 'incremental', status: 'canceled', progress: 19, stage: '已取消', createdAt: '2026-08-26T14:02:00+08:00', updatedAt: '2026-08-26T14:11:00+08:00', operator: '刘阳', added: 0, updated: 23, removed: 0, unchanged: 890, attempts: 1, logs: ['14:02:10 获取 Wiki 快照', '14:09:52 发现源站内容仍在编辑', '14:11:03 操作者取消任务'] },
    ],
    reviewBatches: [
      {
        id: 'review-0905-003', jobId: 'job-0905-003', rule: 'TABLE_STRUCTURE', status: 'pending',
        createdAt: iso('05', '16:43'), submittedAt: null, submittedBy: null,
        items: [
          {
            id: 'review-item-1', order: 1, status: 'pending', severity: 'high',
            pageId: 'wiki-1842-approval', pageTitle: '客户预算调整审批流程',
            path: '销售管理 / 商机推进 / 预算审批', location: '表格 2 · 第 3-5 行',
            issue: '“客户等级”纵向合并，解析器只把 A 类客户写入第一行，第二行失去适用范围。',
            risk: '检索“预算 20 万找谁审批”时，模型可能把大客户负责人错误回答为区域负责人。',
            original: {
              columns: ['客户等级', '预算调整幅度', '审批角色', '处理时限'],
              rows: [
                [{ text: 'A 类客户', rowSpan: 2, flagged: true }, { text: '10 万元以内' }, { text: '区域负责人' }, { text: '4 小时' }],
                [{ skip: true }, { text: '10 万元及以上' }, { text: '大客户负责人' }, { text: '2 小时' }],
                [{ text: 'B 类客户' }, { text: '5 万元及以上' }, { text: '区域负责人' }, { text: '8 小时' }],
              ],
            },
            parsedText: '10 万元以内的预算调整由区域负责人审批，处理时限 4 小时。\n10 万元及以上的预算调整由大客户负责人审批，处理时限 2 小时。\nB 类客户 5 万元及以上由区域负责人审批。',
            suggestedText: 'A 类客户预算调整 10 万元以内，由区域负责人审批，处理时限 4 小时。\nA 类客户预算调整 10 万元及以上，由大客户负责人审批，处理时限 2 小时。\nB 类客户预算调整 5 万元及以上，由区域负责人审批，处理时限 8 小时。',
            decisionNotes: {
              exclude: '该表属于核心审批规则，直接入库可能产生审批人错配。本次先主动排除，保留 Wiki 原文，并由销售运营确认规则有效性后重新摄取。',
              escalate: '纵向合并单元格导致客户等级上下文丢失，影响预算审批人判断。升级给解析工程修复表格展开规则，并用本页作为 TABLE_STRUCTURE 回归样本。',
            },
            recommendedDecision: 'normalize', decision: null, correctedText: '', note: '', reviewer: null, reviewedAt: null,
          },
          {
            id: 'review-item-2', order: 2, status: 'pending', severity: 'medium',
            pageId: 'wiki-1842-onboarding', pageTitle: '新客开户材料清单',
            path: '客户成功 / 新客接入 / 开户准备', location: '表格 1 · 第 6-9 行',
            issue: '“企业客户”分组跨三行合并，解析结果遗漏了后两项材料所属的客户类型。',
            risk: '客服按检索答案准备开户材料时，可能漏掉企业授权书或受益所有人声明。',
            original: {
              columns: ['客户类型', '材料名称', '是否必需', '校验责任人'],
              rows: [
                [{ text: '企业客户', rowSpan: 3, flagged: true }, { text: '营业执照' }, { text: '是' }, { text: '客户成功经理' }],
                [{ skip: true }, { text: '企业授权书' }, { text: '是' }, { text: '销售运营' }],
                [{ skip: true }, { text: '受益所有人声明' }, { text: '高风险行业必需' }, { text: '风险合规' }],
              ],
            },
            parsedText: '企业客户需提供营业执照。\n企业授权书为必需材料，由销售运营校验。\n受益所有人声明仅高风险行业必需。',
            suggestedText: '企业客户开户需提供营业执照，由客户成功经理校验。\n企业客户开户需提供企业授权书，由销售运营校验。\n高风险行业的企业客户还需提供受益所有人声明，由风险合规校验。',
            decisionNotes: {
              exclude: '开户材料属于合规敏感内容，当前解析结果缺少客户类型继承关系。为避免客服提供不完整清单，本次主动排除，待合规负责人确认后重新摄取。',
              escalate: '三行合并的“企业客户”分组未向下展开，导致材料适用对象丢失。升级给解析工程补充分组继承逻辑，并由风险合规复验输出。',
            },
            recommendedDecision: 'normalize', decision: null, correctedText: '', note: '', reviewer: null, reviewedAt: null,
          },
          {
            id: 'review-item-3', order: 3, status: 'pending', severity: 'high',
            pageId: 'wiki-1842-collaboration', pageTitle: '跨区域商机协同响应时效',
            path: '销售管理 / 区域协同 / 服务等级', location: '表格 3 · 双层表头',
            issue: '双层表头同时包含横向与纵向合并，当前解析器把“首次响应”和“解决时限”列错位。',
            risk: '错误 SLA 会影响跨区域线索承接与客户投诉升级，属于高业务影响内容。',
            original: {
              columns: ['商机等级', '工作日 · 首次响应', '工作日 · 解决时限', '节假日 · 首次响应'],
              rows: [
                [{ text: 'S 级' }, { text: '15 分钟', flagged: true }, { text: '2 小时', flagged: true }, { text: '30 分钟' }],
                [{ text: 'A 级' }, { text: '30 分钟' }, { text: '4 小时' }, { text: '1 小时' }],
                [{ text: 'B 级' }, { text: '2 小时' }, { text: '1 个工作日' }, { text: '4 小时' }],
              ],
            },
            parsedText: 'S 级商机：工作日首次响应 2 小时，解决时限 15 分钟；节假日首次响应 30 分钟。\nA 级商机：工作日首次响应 4 小时，解决时限 30 分钟。',
            suggestedText: 'S 级商机在工作日 15 分钟内首次响应、2 小时内解决；节假日 30 分钟内首次响应。\nA 级商机在工作日 30 分钟内首次响应、4 小时内解决；节假日 1 小时内首次响应。\nB 级商机在工作日 2 小时内首次响应、1 个工作日内解决；节假日 4 小时内首次响应。',
            decisionNotes: {
              exclude: 'SLA 字段已经发生列错位，错误答案会直接影响跨区域商机承接。本次先排除该表，继续摄取其他安全内容，待结构修复后单独补录。',
              escalate: '双层表头同时存在横向、纵向合并，解析器把首次响应与解决时限互换。升级为高优先级解析缺陷，由解析工程修复并补充 S/A/B 级 SLA 回归断言。',
            },
            recommendedDecision: 'escalate', decision: null, correctedText: '', note: '', reviewer: null, reviewedAt: null,
          },
        ],
      },
    ],
    versions: [
      { id: 'ver-candidate', collection: 'rag_docs_20260905_001', alias: null, status: 'candidate', documents: 126438, chunks: 1864934, qualityScore: 94.6, qualityGate: 'passed', createdAt: iso('05', '17:30'), operator: '李雯', sourceJobId: 'job-0905-002', notes: '修复销售 SOP 版本并更新账户审核规则' },
      { id: 'ver-active', collection: 'rag_docs_20260901', alias: 'rag_active', status: 'active', documents: 126400, chunks: 1860214, qualityScore: 93.8, qualityGate: 'passed', createdAt: iso('01', '21:36'), operator: '李雯', sourceJobId: 'job-0901-003', notes: '九月基线版本' },
      { id: 'ver-ready', collection: 'rag_docs_20260828', alias: null, status: 'ready', documents: 126312, chunks: 1857480, qualityScore: 92.9, qualityGate: 'passed', createdAt: '2026-08-28T19:18:00+08:00', operator: '陈静', sourceJobId: 'job-0828-002', notes: '客户归属规则更新' },
      { id: 'ver-archived', collection: 'rag_docs_20260820', alias: null, status: 'archived', documents: 125920, chunks: 1849050, qualityScore: 89.4, qualityGate: 'failed', createdAt: '2026-08-20T20:05:00+08:00', operator: '周涵', sourceJobId: 'job-0820-003', notes: '召回率低于门禁，未发布' },
    ],
    datasets: [
      { id: 'ds-crm-smoke', name: 'CRM 核心问答冒烟集', version: 'v1.8', cases: 320, owner: '周涵', updatedAt: iso('03', '10:20') },
      { id: 'ds-acl-negative', name: '租户与 ACL 负向集', version: 'v2.1', cases: 148, owner: '刘阳', updatedAt: iso('02', '18:40') },
      { id: 'ds-sales-sop', name: '销售 SOP 回归集', version: 'v1.3', cases: 206, owner: '李雯', updatedAt: iso('01', '14:10') },
    ],
    evaluations: [
      { id: 'eval-0905-001', versionId: 'ver-candidate', version: 'rag_docs_20260905_001', datasetId: 'ds-crm-smoke', dataset: 'CRM 核心问答冒烟集', status: 'passed', score: 94.6, recall: 96.2, citation: 98.4, grounded: 93.1, aclLeakage: 0, createdAt: iso('05', '17:04'), operator: '周涵' },
      { id: 'eval-0901-002', versionId: 'ver-active', version: 'rag_docs_20260901', datasetId: 'ds-acl-negative', dataset: '租户与 ACL 负向集', status: 'passed', score: 100, recall: 100, citation: 100, grounded: 100, aclLeakage: 0, createdAt: iso('01', '20:58'), operator: '刘阳' },
      { id: 'eval-0820-001', versionId: 'ver-archived', version: 'rag_docs_20260820', datasetId: 'ds-sales-sop', dataset: '销售 SOP 回归集', status: 'failed', score: 89.4, recall: 86.8, citation: 95.2, grounded: 91.0, aclLeakage: 0, createdAt: '2026-08-20T19:10:00+08:00', operator: '周涵', error: 'Recall@10 低于 90% 发布阈值' },
    ],
    onlineEffect: {
      generatedAt: iso('06', '09:10'),
      scale: { workspaces: 18, registeredUsers: 640, dailyActiveUsers: 190, dailyQuestions: 4600 },
      scope: {
        currentVersion: 'rag_docs_20260901',
        baselineVersion: 'rag_docs_20260828',
        releasedAt: '2026-09-01T09:00:00+08:00',
      },
      trends: [
        { date: '08/24', questions: 4380, selfResolved: 69.9, unresolved: 22.6, repeatQuery: 18.2, negativeFeedback: 10.1, taskCompletion: 73.8, adoption: 67.9, p95: 4.92 },
        { date: '08/25', questions: 4510, selfResolved: 70.2, unresolved: 22.3, repeatQuery: 18.0, negativeFeedback: 9.9, taskCompletion: 74.0, adoption: 68.2, p95: 4.88 },
        { date: '08/26', questions: 4460, selfResolved: 70.6, unresolved: 22.0, repeatQuery: 17.8, negativeFeedback: 9.8, taskCompletion: 74.3, adoption: 68.8, p95: 4.86 },
        { date: '08/27', questions: 4620, selfResolved: 70.4, unresolved: 21.8, repeatQuery: 17.7, negativeFeedback: 9.7, taskCompletion: 74.4, adoption: 68.5, p95: 4.83 },
        { date: '08/28', questions: 4710, selfResolved: 71.0, unresolved: 21.6, repeatQuery: 17.4, negativeFeedback: 9.6, taskCompletion: 74.9, adoption: 69.0, p95: 4.79 },
        { date: '08/29', questions: 4550, selfResolved: 70.5, unresolved: 21.9, repeatQuery: 17.8, negativeFeedback: 9.9, taskCompletion: 74.5, adoption: 68.6, p95: 4.87 },
        { date: '08/30', questions: 4210, selfResolved: 71.2, unresolved: 21.3, repeatQuery: 17.2, negativeFeedback: 9.5, taskCompletion: 75.1, adoption: 69.1, p95: 4.72 },
        { date: '08/31', questions: 4330, selfResolved: 70.8, unresolved: 21.9, repeatQuery: 17.6, negativeFeedback: 9.8, taskCompletion: 74.6, adoption: 68.7, p95: 4.85 },
        { date: '09/01', questions: 4590, selfResolved: 76.9, unresolved: 18.7, repeatQuery: 14.8, negativeFeedback: 7.6, taskCompletion: 80.1, adoption: 73.8, p95: 3.46, release: true },
        { date: '09/02', questions: 4680, selfResolved: 78.2, unresolved: 17.9, repeatQuery: 13.9, negativeFeedback: 7.1, taskCompletion: 81.7, adoption: 74.9, p95: 3.29 },
        { date: '09/03', questions: 4750, selfResolved: 79.4, unresolved: 17.1, repeatQuery: 12.8, negativeFeedback: 6.7, taskCompletion: 82.9, adoption: 75.6, p95: 3.18 },
        { date: '09/04', questions: 4630, selfResolved: 80.3, unresolved: 16.8, repeatQuery: 12.1, negativeFeedback: 6.4, taskCompletion: 83.8, adoption: 76.0, p95: 3.12 },
        { date: '09/05', questions: 4810, selfResolved: 80.9, unresolved: 16.5, repeatQuery: 11.7, negativeFeedback: 6.1, taskCompletion: 84.6, adoption: 76.3, p95: 3.09 },
        { date: '09/06', questions: 4600, selfResolved: 81.4, unresolved: 16.2, repeatQuery: 11.3, negativeFeedback: 5.9, taskCompletion: 85.2, adoption: 76.5, p95: 3.08 },
      ],
      dimensions: {
        tenant: [
          { id: 'crm-demo', name: '商业平台 · 客户运营', samples: 9200, selfResolved: 83.1, unresolved: 14.0, repeatQuery: 9.8, negativeFeedback: 4.8, taskCompletion: 87.4, adoption: 78.7, failures: 14 },
          { id: 'crm-enterprise', name: '大客户业务支持', samples: 6880, selfResolved: 82.0, unresolved: 15.2, repeatQuery: 10.5, negativeFeedback: 5.2, taskCompletion: 86.3, adoption: 77.8, failures: 12 },
          { id: 'crm-north', name: '华北渠道运营', samples: 4490, selfResolved: 76.8, unresolved: 20.4, repeatQuery: 15.6, negativeFeedback: 8.1, taskCompletion: 79.2, adoption: 71.5, failures: 18 },
          { id: 'crm-success', name: '客户成功中心', samples: 4240, selfResolved: 81.7, unresolved: 15.6, repeatQuery: 10.9, negativeFeedback: 5.6, taskCompletion: 86.8, adoption: 77.1, failures: 9 },
          { id: 'crm-risk', name: '风险与审核支持', samples: 3250, selfResolved: 79.5, unresolved: 17.2, repeatQuery: 12.4, negativeFeedback: 6.3, taskCompletion: 83.9, adoption: 74.8, failures: 7 },
        ],
        business: [
          { id: 'delivery', name: '搜索推广投放诊断', samples: 8240, selfResolved: 83.5, unresolved: 13.7, repeatQuery: 9.4, negativeFeedback: 4.7, taskCompletion: 88.0, adoption: 79.2, failures: 13 },
          { id: 'account', name: '客户开户与资质', samples: 6280, selfResolved: 80.9, unresolved: 16.5, repeatQuery: 11.2, negativeFeedback: 5.8, taskCompletion: 86.1, adoption: 76.2, failures: 11 },
          { id: 'policy', name: '产品政策与计费', samples: 5820, selfResolved: 81.2, unresolved: 15.6, repeatQuery: 10.8, negativeFeedback: 5.5, taskCompletion: 83.4, adoption: 77.0, failures: 15 },
          { id: 'assignment', name: '客户归属与区域协同', samples: 4200, selfResolved: 75.6, unresolved: 21.8, repeatQuery: 16.9, negativeFeedback: 8.7, taskCompletion: 78.1, adoption: 70.4, failures: 17 },
          { id: 'risk', name: '账户审核与风险处置', samples: 3520, selfResolved: 80.0, unresolved: 16.7, repeatQuery: 11.8, negativeFeedback: 6.1, taskCompletion: 84.6, adoption: 75.9, failures: 8 },
        ],
        issue: [
          { id: 'fact', name: '事实查询', samples: 9780, selfResolved: 86.1, unresolved: 10.2, repeatQuery: 7.1, negativeFeedback: 3.8, taskCompletion: 89.4, adoption: 82.4, failures: 8 },
          { id: 'procedure', name: '流程操作', samples: 7250, selfResolved: 82.3, unresolved: 14.6, repeatQuery: 9.9, negativeFeedback: 5.0, taskCompletion: 88.2, adoption: 78.1, failures: 11 },
          { id: 'diagnosis', name: '故障诊断', samples: 5700, selfResolved: 77.4, unresolved: 19.3, repeatQuery: 15.2, negativeFeedback: 7.7, taskCompletion: 80.6, adoption: 72.5, failures: 16 },
          { id: 'policy', name: '政策口径', samples: 3670, selfResolved: 79.0, unresolved: 17.5, repeatQuery: 12.6, negativeFeedback: 6.4, taskCompletion: 82.8, adoption: 75.0, failures: 13 },
          { id: 'multihop', name: '跨系统多跳', samples: 1660, selfResolved: 68.4, unresolved: 29.1, repeatQuery: 23.8, negativeFeedback: 12.4, taskCompletion: 70.3, adoption: 63.8, failures: 16 },
        ],
      },
      experiment: {
        id: 'exp-rag-20260901', name: '九月检索与快慢路径升级', status: 'running', owner: '陈静', startedAt: '2026-09-01T09:00:00+08:00', traffic: 50,
        control: { label: 'A 基线组', version: 'rag_docs_20260828', samples: 13970, selfResolved: 70.8, unresolved: 21.9, repeatQuery: 17.6, negativeFeedback: 9.8, taskCompletion: 74.6, adoption: 68.7, p95: 4.85, tokens: 4980 },
        treatment: { label: 'B 候选组', version: 'rag_docs_20260901', samples: 14090, selfResolved: 81.4, unresolved: 16.2, repeatQuery: 11.3, negativeFeedback: 5.9, taskCompletion: 85.2, adoption: 76.5, p95: 3.08, tokens: 3760 },
        confidence: 99.2, guardrails: { aclLeakage: 0, highRiskWrongAnswers: 0, duplicateSideEffects: 0 },
      },
      failures: [
        { id: 'conv-0906-1842', time: '09/06 08:42', tenantId: 'crm-north', tenant: '华北渠道运营', businessId: 'assignment', business: '客户归属', issueId: 'multihop', issue: '跨系统多跳', group: 'B', risk: 'high', metric: 'unresolved', reason: '区域过渡期例外规则未进入前 10', query: '客户从北京直营迁到河北代理后，本月商机算谁的？', answer: '系统只找到通用归属规则，未获得河北过渡期补充通知，因证据不足未给出结论。', citation: '客户归属通用规则 · 第 4.2 节', action: '用户点击“未解决”；是否随后去如流求助，本系统不可观测。', trace: ['识别客户迁移意图', '召回通用归属规则', '区域例外证据缺失', '触发高风险拒答'] },
        { id: 'conv-0906-1731', time: '09/06 08:17', tenantId: 'crm-demo', tenant: '商业平台 · 客户运营', businessId: 'delivery', business: '投放诊断', issueId: 'diagnosis', issue: '故障诊断', group: 'B', risk: 'medium', metric: 'repeatQuery', reason: '决策树的前置条件被切到不同 Chunk', query: '计划审核通过了还是没量，先查什么？', answer: '建议先检查出价和预算，但未结合账户余额与地域限制完成分支判断。', citation: '投放异常排查 SOP · 计划级排查', action: '用户 6 分钟后改写问题再次询问。', trace: ['识别无量诊断', '召回 6 个排查 Chunk', '评分器未恢复条件顺序', '检测到同意图重复提问'] },
        { id: 'conv-0906-1614', time: '09/06 07:56', tenantId: 'crm-risk', tenant: '风险与审核支持', businessId: 'risk', business: '账户审核', issueId: 'policy', issue: '政策口径', group: 'B', risk: 'high', metric: 'negativeFeedback', reason: '回答包含两个结论，引用只支持其中一个', query: '高风险行业开户需要什么材料，由谁复核？', answer: '回答正确列出材料，但引用段落没有直接支持“风险合规复核”的责任人结论。', citation: '新客开户材料清单 · 表 1', action: '用户提交“引用不完整”负反馈。', trace: ['拆解材料与责任人两个 Claim', '材料证据通过', '责任人证据不足', '记录引用无效反馈'] },
        { id: 'conv-0905-1498', time: '09/05 17:20', tenantId: 'crm-enterprise', tenant: '大客户业务支持', businessId: 'policy', business: '产品计费', issueId: 'policy', issue: '政策口径', group: 'B', risk: 'high', metric: 'unresolved', reason: '返点需要组合全国政策与区域补充通知', query: '华东 KA 客户转代理后，已承诺返点按什么口径结算？', answer: '已找到全国返点政策，但区域过渡期补充通知未命中，系统拒绝生成金额结论。', citation: '第三季度 KA 返点政策 · 第 3 章', action: '用户点击“未解决”；系统不推断后续跨系统求助行为。', trace: ['检索全国政策', '识别区域限定', '补充通知排名第 13', '触发金额类拒答'] },
        { id: 'conv-0905-1337', time: '09/05 15:46', tenantId: 'crm-success', tenant: '客户成功中心', businessId: 'account', business: '客户开户', issueId: 'procedure', issue: '流程操作', group: 'A', risk: 'medium', metric: 'taskCompletion', reason: '操作步骤只存在截图中，纯文本摄取未覆盖', query: '新建客户后如何把商机关联到总部账户？', answer: '只返回了原始操作手册链接，没有生成未受证据支持的点击步骤。', citation: 'CRM 商机关联手册 · 第 2 页', action: '用户打开原文，但关联商机任务未在统计窗口内完成。', trace: ['召回操作手册', '检测到步骤依赖图片', '禁止猜测界面步骤', '任务完成事件缺失'] },
        { id: 'conv-0905-1182', time: '09/05 13:08', tenantId: 'crm-demo', tenant: '商业平台 · 客户运营', businessId: 'delivery', business: '投放诊断', issueId: 'fact', issue: '事实查询', group: 'B', risk: 'low', metric: 'repeatQuery', reason: '错误码在向量召回中排序偏后', query: '投放平台报 E1027 是什么意思？', answer: '返回了通用授权过期说明，但没有命中 E1027 专用处置页。', citation: '投放平台常见授权错误', action: '用户 3 分钟后补充完整错误码重新询问。', trace: ['向量召回 20 条', 'BM25 未开启错误码专用通道', '目标文档排名第 12', '检测到同意图重复提问'] },
      ],
      alertRules: [
        { id: 'rule-risk', name: '高风险错答护栏', metric: 'highRiskWrongAnswers', operator: '>', threshold: 0, window: '5 分钟', minSamples: 1, consecutive: 1, action: 'rollback', rollbackVersion: 'rag_docs_20260828', owner: '风险合规', channel: '电话 + IM', enabled: true, status: 'healthy', lastCheckedAt: iso('06', '09:08') },
        { id: 'rule-resolved', name: '自助解决率下降', metric: 'selfResolved', operator: '<', threshold: 76, window: '30 分钟', minSamples: 300, consecutive: 2, action: 'pause', rollbackVersion: null, owner: '知识运营', channel: '监控群', enabled: true, status: 'healthy', lastCheckedAt: iso('06', '09:05') },
        { id: 'rule-unresolved', name: '未解决率上升', metric: 'unresolved', operator: '>', threshold: 19, window: '30 分钟', minSamples: 300, consecutive: 3, action: 'alert', rollbackVersion: null, owner: '客户成功', channel: '监控群', enabled: true, status: 'watching', lastCheckedAt: iso('06', '09:05') },
        { id: 'rule-negative', name: '负反馈率上升', metric: 'negativeFeedback', operator: '>', threshold: 8, window: '1 小时', minSamples: 200, consecutive: 2, action: 'alert', rollbackVersion: null, owner: '知识运营', channel: '监控群', enabled: true, status: 'healthy', lastCheckedAt: iso('06', '09:06') },
        { id: 'rule-completion', name: '任务完成率下降', metric: 'taskCompletion', operator: '<', threshold: 80, window: '1 小时', minSamples: 120, consecutive: 2, action: 'pause', rollbackVersion: null, owner: 'CRM 产品运营', channel: '邮件 + IM', enabled: true, status: 'healthy', lastCheckedAt: iso('06', '09:07') },
        { id: 'rule-acl', name: 'ACL 越权泄漏', metric: 'aclLeakage', operator: '>', threshold: 0, window: '1 分钟', minSamples: 1, consecutive: 1, action: 'rollback', rollbackVersion: 'rag_docs_20260828', owner: '安全负责人', channel: '电话 + IM', enabled: true, status: 'healthy', lastCheckedAt: iso('06', '09:09') },
      ],
    },
    audits: [
      { id: 'audit-1', time: iso('05', '17:32'), actor: '李雯', action: 'QUALITY_GATE_APPROVED', target: 'rag_docs_20260905_001', result: 'success', ip: '10.24.18.36', requestId: 'req-quality-0905', detail: '质量门禁 4/4 通过，允许进入发布审批。' },
      { id: 'audit-2', time: iso('05', '16:43'), actor: '系统', action: 'INGESTION_BLOCKED', target: 'crm-demo-20260905-003', result: 'denied', ip: 'service', requestId: 'req-ingest-0905-003', detail: '复杂表格结构检查失败，阻断摄取任务。' },
      { id: 'audit-3', time: iso('04', '23:10'), actor: '周涵', action: 'SOURCE_SYNCED', target: '账户审核与风险处置规范', result: 'success', ip: '10.24.21.18', requestId: 'req-sync-0904', detail: '对象存储快照同步完成，0 个高风险删除。' },
      { id: 'audit-4', time: iso('01', '21:36'), actor: '李雯', action: 'ALIAS_ACTIVATED', target: 'rag_active → rag_docs_20260901', result: 'success', ip: '10.24.18.36', requestId: 'req-release-0901', detail: '完成 CAS 校验后切换线上检索别名。' },
      { id: 'audit-5', time: '2026-08-28T18:55:00+08:00', actor: '系统', action: 'JOB_RESUMED', target: 'crm-demo-20260828-002', result: 'success', ip: 'worker-02', requestId: 'req-resume-0828', detail: '从已持久化 checkpoint 恢复剩余操作。' },
    ],
    notifications: [
      { id: 'notice-1', type: 'warning', title: '摄取任务需要人工复核', body: '销售与客户成功 SOP 检测到复杂表格。', time: iso('05', '16:43'), read: false, route: '/jobs/review?job=job-0905-003' },
      { id: 'notice-2', type: 'success', title: '候选版本通过质量门禁', body: 'rag_docs_20260905_001 已可发布。', time: iso('05', '17:32'), read: false, route: '/versions' },
      { id: 'notice-3', type: 'info', title: 'Wiki 同步凭据即将轮换', body: '凭据将在 7 天后到期，请安排轮换。', time: iso('04', '09:10'), read: true, route: '/settings' },
    ],
    settings: {
      environment: 'simulation',
      milvus: { uri: 'https://milvus.crm.example.test:19530', collectionPrefix: 'rag_docs_', activeAlias: 'rag_active', status: 'healthy', lastCheckedAt: iso('05', '17:45') },
      embedding: { provider: 'OpenAI Compatible Gateway', model: 'text-embedding-3-large', dimensions: 3072, status: 'healthy', lastCheckedAt: iso('05', '17:46') },
      reranker: { provider: 'Local CrossEncoder', model: 'bge-reranker-v2-m3', timeoutSeconds: 2.5, status: 'healthy', lastCheckedAt: iso('05', '17:46') },
      wiki: { baseUrl: 'https://wiki.example.test', credentialRef: 'vault://crm/wiki-reader', status: 'healthy', lastCheckedAt: iso('05', '17:42') },
      objectStorage: { endpoint: 'https://s3.example.test', bucket: 'crm-knowledge', credentialRef: 'vault://crm/object-reader', status: 'healthy', lastCheckedAt: iso('05', '17:43') },
      security: { requireApproval: true, blockHighRiskDelete: true, highRiskDeletePercent: 5, retainVersions: 5, auditRetentionDays: 180 },
    },
  };
}
